### ISSUE TITLE
Civilization: Vikings

### ISSUE THREAD

**Issue by niektb** [0ADMods/millenniumad#12]
Tasks:
- [x] Create JSON. WIP, technology + hero descriptions should be added
- [x] implement soundtracks.
- [x] Create techs
- [x] Create bonuses
- [x] Create buildings / units

**Comment by makiman83** [comment]
Hi there.
I´m testing this mod and would like to know hot to modify de experience points of the civil-soldiers. I see that today is so high, about 100.00.000 in axemen, so, it is very dificult to get.
Than you for your attention.

**Comment by niektb** [comment]
Currently that's because 0 A.D. has made it impossible to promote (by raising the required amount of experience points) and that has nothing to do with the mod. 
That's changed back to 100XP in the developer version of 0 A.D. and so will it be in Alpha 19. Please note that the developer version is required to play Millennium A.D. properly:
http://trac.wildfiregames.com/wiki/BuildInstructions

**Comment by makiman83** [comment]
Thank you your answer. Understood.
