### ISSUE TITLE
Unable to open/play maps.

### ISSUE THREAD

**Issue by s0600204** [0ADMods/millenniumad#16]
I'm having problems with Millennium AD's maps, and thought I'd report them here.

Firstly, some observations:
* The file `Norse Migration Test.pmp.xml` needs renaming to `Norse Migration Test.xml`
* "Stormy water test" has a given name of "Unnamed map"

And my main problem: If I try opening any of the four maps provided by this mod, 0AD crashes to Desktop.
* *interestinglog.html* is empty
* *mainlog.html* reports `CTerrainTextureManager::RecurseDirectory(art/terrains/): no terrains.xml (or errors while loading) - using parent properties`
* *crashlog.txt* reads
```
Assertion failed: "0 && (L"Invalid map XML data")"
Location: MapReader.cpp:788 (ReadEnvironment)

Call stack:

(0x8ff41b) /usr/bin/pyrogenesis() [0x8ff41b]
(0x8b8dd1) /usr/bin/pyrogenesis() [0x8b8dd1]
(0x8ba63a) /usr/bin/pyrogenesis() [0x8ba63a]
(0x6dac0e) /usr/bin/pyrogenesis() [0x6dac0e]
(0x6e317d) /usr/bin/pyrogenesis() [0x6e317d]
(0x6e341e) /usr/bin/pyrogenesis() [0x6e341e]
(0x6d7658) /usr/bin/pyrogenesis() [0x6d7658]
(0x5f345e) /usr/bin/pyrogenesis() [0x5f345e]
(0x431f79) /usr/bin/pyrogenesis() [0x431f79]
(0x421a37) /usr/bin/pyrogenesis() [0x421a37]
(0x7fe17cbcb800) /usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7fe17cbcb800]
(0x430b79) /usr/bin/pyrogenesis() [0x430b79]

errno = 0 (No error reported here)
OS error = ?
```
I also cannot open any of them in the Map Editor.

For reference, I'm running **A18** on Arch Linux 64-bit, and I have no problems with 0AD's own maps.

They'll also need to be converted to the new A19 format eventually...

**Comment by StanleySweet** [comment]
I don't think we converted them to the new format. In fact there is no trace of such thing in the commit history. So it's really weird you can't open them with A18...

**Comment by niektb** [comment]
The map format have had actually 2 changes: the height and the colour/color. The latter is implemented (which makes them incompatible with A18), the former is not (which make them incompatible with SVN/A19 too). I figure they should be converted to the new format.

**Comment by s0600204** [comment]
Ah yes, switching *`Color` => *`Colour` resolves that problem, and the maps load. However, they're still not 'playable'.

Both `Fjords.xml` and `Norse Migration Test.xml` complain about missing entities:

Fjords:
 - art/actors/props/wooden_cart_big.xml
 - art/actors/props/structures/chin_barrel.xml (is this a han_china prop?)

Norse Migration Test:
 - simulation/templates/units/norse_hero_britomartus.xml
 - simulation/templates/units/norse_warship_2.xml
 - simulation/templates/units/norse_hero_brennus.xml
 - simulation/templates/units/norse_warship_2.xml
 - simulation/templates/units/norse_hero_britomartus.xml
 - simulation/templates/units/norse_hero_brennus.xml

`Sandbox - Norse` loads fine, but the player is not given any units and no structures other than palisade walls...

And `stormy water test`? Six of the seven Petra/AI opponents report that "it does not know how to interpret this map" and then resigns. Quite possibly because neither they nor the player have any structures or units (Player 2 does, though). It would be nice it the map's description informed players that this is a test map that shouldn't really be played...

**Comment by niektb** [comment]
Ah yes, Stormy Water Test was nothing but a showcase made I used to write a story around (Hvanndalir): http://www.moddb.com/mods/millennium-ad/news/development-update-september-2014
