### ISSUE TITLE
Viking Blacksmith has no texture

### ISSUE THREAD

**Issue by StanleySweet** [0ADMods/millenniumad#23]

**Comment by niektb** [comment]
How's that possible? It always worked?

**Comment by StanleySweet** [comment]
Yes but it was probably moved

2016-07-16 18:05 GMT+02:00 Niek ten Brinke <notifications@github.com>:

**Comment by niektb** [comment]
Ah yes, forgot about that monstrous texture movement :/

**Comment by niektb** [comment]
Is fixed nowadays
