### ISSUE TITLE
Fortress unable to shoot

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/millenniumad#25]
Issue: Enemy unit in range of fortress, `attachpoint` error appears. The effect the enemy unit does not get hurt. 

Expected behavior: Fortress can shoot

Version: Millennium A.D. from ModDB + 0 A.D. 21

Fraction: Carolingian

**Comment by StanleySweet** [comment]
I'll look into that in the coming week hopefully.

**Comment by niektb** [comment]
The Carolingian faction is untested and still under construction, so I don't think you should expect it to work. Did I forget to make it unselectable?

**Comment by Jeeppler** [comment]
Yes, in this case you did forget to make them unselectable.

**Comment by StanleySweet** [comment]
@AlexanderVzla  @wackyserious  Is this fixed ?

**Comment by AlexanderVzla** [comment]
Caro fortress was missing prop-projectile in both dae and actor now shoots.
