### ISSUE TITLE
byza_wall_gate units going through locked.

### ISSUE THREAD

**Issue by AlexanderVzla** [0ADMods/millenniumad#30]
Enemies or player infantry can go through the gate walls in locked state.

A fix is going to be committed soon i need someone to test it.

Reported by Servo in the forums.

https://wildfiregames.com/forum/index.php?/topic/24659-millennium-ad-x%C3%BDlo-23-now-available/&page=2&tab=comments#comment-360491

**Comment by tomasmatys** [comment]
ok as confirmed here https://wildfiregames.com/forum/index.php?/topic/24659-millennium-ad-x%C3%BDlo-23-now-available/&page=3&tab=comments#comment-360705 it got fixed
