### ISSUE TITLE
 Royal Theng cover 

### ISSUE THREAD

**Issue by tomasmatys** [0ADMods/millenniumad#33]

**Comment by niektb** [comment]
What's with it?

**Comment by tomasmatys** [comment]
well ask wackyserious he stated that it needs to be changed https://www.moddb.com/mods/millennium-ad/news/xlo-23-now-available

**Comment by Jeeppler** [comment]
@tomasmatys can you be a little bit more specific? Your current issue description is far to general.

**Comment by tomasmatys** [comment]
Not enough info, @wackyserious  if you have something new concerning this Issue feel free to reopen.
