### ISSUE TITLE
missing Carolingian heroes

### ISSUE THREAD

**Issue by tomasmatys** [0ADMods/millenniumad#35]
https://wildfiregames.com/forum/index.php?/topic/24332-discussion-heroes/&tab=comments#comment-353939

**Comment by Jeeppler** [comment]
Carolingian heroes:

 - [Charlemagne](https://en.wikipedia.org/wiki/Charlemagne) 
 - [Charles Martel ﻿](https://en.wikipedia.org/wiki/Charles_Martel)

**Comment by tomasmatys** [comment]
@Jeeppler  do we know each other from forums?

**Comment by tomasmatys** [comment]
addressed
