### ISSUE TITLE
[Anglo-Saxons] Same logo for Heroes

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/millenniumad#42]
Anglo-Saxons have two heroes: 

- [Offa of Mercia](https://en.wikipedia.org/wiki/Offa_of_Mercia)
- [Alfred the Great](https://en.wikipedia.org/wiki/Alfred_the_Great)

However, both have the same logo on their button. This is confusing. Please give both a separate logo, which makes it easy to understand whom to pick.

**Comment by tomasmatys** [comment]
@Jeeppler That is known thing as a reader of forums we wanted and still, want to have unique portraits but our artists as always are undermanned and very busy since guys who develop these mods also develop core vanilla version of 0AD.

**Comment by Jeeppler** [comment]
@tomasmatys whenever artist have time they can look at this issue and solve it. That is the purpose of an issue tracker.
