### ISSUE TITLE
siege technologies outdated

### ISSUE THREAD

**Issue by SlavomirSlovenkai** [0ADMods/millenniumad#68]
Hi,
siege techs in arsenal and some more structures does not exist anymore.
This is correct list  available.
 <Technologies datatype="tokens">
      siege_attack
      siege_cost_time
      siege_health
      siege_pack_unpack
      siege_bolt_accuracy
    </Technologies>
I think this is causing also ai issue because template for those structures does not parse.
Reproducable in structure tree also.

@StanleySweet

**Comment by StanleySweet** [comment]
I suggest we use the default vanilla techs where possible. We don't have the resources to provide balancing for the mod.
