### ISSUE TITLE
The han are totally inacurate

### ISSUE THREAD

**Issue by StanleySweet** [0ADMods/millenniumad#73]
@wltonlopes why did you commit the Han to millenium AD? It makes no sense :(

Even if it was a good idea it uses the old assets....

**Comment by wltonlopes** [comment]
I will undo this was not for the official mod but for a side project with the [steriotype](https://github.com/stereotipo/millenniumad/tree/chineses)

**Comment by StanleySweet** [comment]
Thanks.
