### ISSUE TITLE
Installation guide on mod.io refers to "Terra Magna" instead of "Millennium A.D."

### ISSUE THREAD

**Issue by 7wells** [0ADMods/millenniumad#78]
Hello!

The installation guide on mod.io mentions "Terra Magna" instead of "Millennium A.D.":
> **In-Game Installation:**
> 1. Main menu -> Settings -> Mod Selection -> Download Mods
> 2. Accept the mod.io terms and conditions
> 3. Find **Terra Magna** in the mods list and double-click to download
> 4. Once it's complete, chose **Terra Magna** from your list and double-click it to add it to Enabled Mods at the bottom of the screen
> 5. Press 'Save and Restart.'
> 6. Enjoy the mod!

**Comment by JustusAvramenko** [comment]
Fixed. Thanks!
