### ISSUE TITLE
Civilization music

### ISSUE THREAD

**Issue by niektb** [0ADMods/millenniumad#9]
We should seek to provide a few soundtracks for each civilization.
- [x] Vikings

**Comment by Jeeppler** [comment]
Is this done? Or is this just closed, because of age? 

The Holiday Commit [#9](https://github.com/0ADMods/millenniumad/commit/d71ac993bc254231d76ff8c7bef8365f80b8be30) does not add any music.

**Comment by StanleySweet** [comment]
Music has been added  as depicted in the credits. So a bit of both :)
